### ISSUE TITLE
Вор.

### ISSUE THREAD

**Issue by nsvk13** [omashune/HeadsAnywhere#1]
Воровать проекты — не красиво.
RecoveryHeads.

Обманывать других, выставляя чужое за свою работу —  не красиво.
Этого мы так не оставим.
Удаляй свои ресурсы с spigotmc.

**Comment by omashune** [comment]
Ты б для начала посмотрел, кто писал оригинальный плагин

**Comment by nsvk13** [comment]
а я знаю.

**Comment by omashune** [comment]
Ну, раз знаешь, то не пишите свою чушь в этот раздел, он не для этого предназначен. Если хочешь пообщаться - телеграм https://t.me/omashune
![author](https://github.com/omashune/HeadsAnywhere/assets/37953543/ac9abfa4-f1a7-4ec4-8670-56bd659bf701)
